import Head from 'next/head'
import React from 'react'
import userLayout from '../../layouts/userLayout'
import TicketComponent from '../../components/ticket'

const Ticket = () => {
  return (
    <div className='myContainer mt-12'>
      <Head>
        <title>Ticket</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <TicketComponent/>
    </div>
  )
}

export default Ticket
Ticket.layout = userLayout