import Head from 'next/head'
import React from 'react'
import userLayout from '../../layouts/userLayout'
import PlaceOrderForGuestList from '../../components/placeOrder/placeOrderForGuestList'
import HotelListContent from '../../components/hotelListContent'

const HotelList = () => {
  return (
    <div>
       <Head>
        <title>Hotel List</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <PlaceOrderForGuestList/>
      <HotelListContent/>
    </div>
  )
}

export default HotelList
HotelList.layout = userLayout