import Head from 'next/head'
import React from 'react'
import userLayout from '../../layouts/userLayout'
import PlaceOrderForGuest from '../../components/placeOrder/placeOrderForGuest'
import HotelHero from '../../components/hero/hotelHero'
import TravelPrice from '../../components/travelPrice'
import LocationAbout from '../../components/locationAbout'
import RecentSearches from '../../components/recentSearches'

const Hotel = () => {
  return (
    <div>
      <Head>
        <title>Hotel</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <HotelHero/>
      <RecentSearches/>
      <TravelPrice/>
      <LocationAbout/>
    </div>
  )
}

export default Hotel
Hotel.layout = userLayout