import Head from "next/head"
import BookingDetailComponent from "../../components/booking-detail-components"
import userLayout from "../../layouts/userLayout"


const BookingDetail = () => {
  return (
    <div className="myContainer">
       <Head>
        <title>Booking detail</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
    <BookingDetailComponent/>
    </div>
  )
}

export default BookingDetail
BookingDetail.layout = userLayout
