import Head from 'next/head'
import React from 'react'
import userLayout from '../../layouts/userLayout'
import PlaceOrderForFlightList from '../../components/placeOrder/placeOrderForFlightList'
import FlightListContent from '../../components/fligtListContent'

const FlightList = () => {
  return (
    <div className='myContainer mt-12'>
       <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <PlaceOrderForFlightList/>
      <FlightListContent/>
    </div>
  )
}

export default FlightList
FlightList.layout = userLayout
