import Head from "next/head";
import { useEffect } from "react";
import FlightHero from "../../components/hero/flightHero";
import Map from "../../components/map";
import TravelPrice from "../../components/travelPrice";
import LocationAbout from "../../components/locationAbout";
import userLayout from "../../layouts/userLayout";
export default function Home() {
 
  return (
    <div>
      <Head>
        <title>Flight</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <FlightHero />
      <Map />
      <TravelPrice />
      <LocationAbout />
    </div>
  );
}
Home.layout = userLayout;
