import Head from "next/head";
import noneLayout from "../layouts/noneLayout";

export default function Custom500() {


    return (
        <>
            <Head>
                <title>500 eror</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/Fav.png" />
            </Head>
            <div style={{width: "100vw", height: "100vh", position: "relative"}}>
            <h1 style={{position: "absolute", top: "40%", left: "50%", transform: "translateX(-50%)"}}>404 - Page Not Found</h1>
            </div>
        </>
    )
}

Custom500.layout = noneLayout;