import React from 'react'
import Head from 'next/head'
import HomeLayout from '../layouts/homeLayout'
import Hero from '../components/hero'
import TravelList from '../components/travelList'
import Reviews from '../components/reviews'

const Home = () => {
  return (
    <div className=''>
      <Head>
        <title>Traveling Site</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Hero/>
      <TravelList/>
      <Reviews/>
    </div>
  )
}

export default Home
Home.layout = HomeLayout